/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-04-04

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4xx_it.h"

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
static uint32_t volatile msTicks=0;

int main(void)
{
	SysTick_Config(SystemCoreClock/1000);

	uint8_t led_dice[] = { 0x01, 0x18, 0x19, 0x5A, 0x5B, 0x7E };
	uint8_t seg[] = { 0x6, 0x5B, 0x4F, 0x66, 0x6D, 0x7D };

	/* Enable GPIOA, GPIOB, GPIOC */
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN);
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN);
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
	__IO uint32_t tempreg = READ_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN);

	/* Clear GPIOA values */
	GPIOA->MODER &= ~(GPIO_MODER_MODER4 |
	GPIO_MODER_MODER5 | GPIO_MODER_MODER6 |
	GPIO_MODER_MODER7 | GPIO_MODER_MODER8 |
	GPIO_MODER_MODER9 | GPIO_MODER_MODER10 |
	GPIO_MODER_MODER11);

	/* Set GPIOA as output */
	GPIOA->MODER |= (GPIO_MODER_MODER4_0 |
	GPIO_MODER_MODER5_0 | GPIO_MODER_MODER6_0 |
	GPIO_MODER_MODER7_0 | GPIO_MODER_MODER8_0 |
	GPIO_MODER_MODER9_0 | GPIO_MODER_MODER10_0|
	GPIO_MODER_MODER11_0);

	/* Clear GPIOC values */
	GPIOC->MODER &= ~(GPIO_MODER_MODER0 |
	GPIO_MODER_MODER1 | GPIO_MODER_MODER2 |
	GPIO_MODER_MODER3 | GPIO_MODER_MODER4 |
	GPIO_MODER_MODER4 | GPIO_MODER_MODER5|
	GPIO_MODER_MODER6 | GPIO_MODER_MODER7);

	/* Set GPIOC as output */
	GPIOC->MODER |= (GPIO_MODER_MODER0_0 |
	GPIO_MODER_MODER1_0 | GPIO_MODER_MODER2_0 |
	GPIO_MODER_MODER3_0 | GPIO_MODER_MODER4_0 |
	GPIO_MODER_MODER5_0 | GPIO_MODER_MODER6_0|
	GPIO_MODER_MODER7_0);

	/* Set port B pin 0 to input*/
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
	tempreg = READ_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
	CLEAR_BIT(GPIOB->MODER, GPIO_MODER_MODER0);
	CLEAR_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0);
	SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0);
	CLEAR_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR0_0);
	SET_BIT(GPIOB->PUPDR, GPIO_PUPDR_PUPDR0_0);

	/* Turn off all LEDs, GPIOA*/
	CLEAR_BIT(GPIOA->ODR, GPIO_ODR_ODR_4 | GPIO_ODR_ODR_5
	| GPIO_ODR_ODR_6 | GPIO_ODR_ODR_7 | GPIO_ODR_ODR_8
	| GPIO_ODR_ODR_8 | GPIO_ODR_ODR_9 | GPIO_ODR_ODR_10|
	GPIO_ODR_ODR_11);

	/* Turn off all LEDs, GPIOC*/
	CLEAR_BIT(GPIOC->ODR, GPIO_ODR_ODR_0 | GPIO_ODR_ODR_1
	| GPIO_ODR_ODR_2 | GPIO_ODR_ODR_3 | GPIO_ODR_ODR_4
	| GPIO_ODR_ODR_5 | GPIO_ODR_ODR_6 | GPIO_ODR_ODR_7 |
	GPIO_ODR_ODR_8);

	int i = 0;

	/* Infinite loop*/
	while (1) {
		if(!READ_BIT(GPIOB->IDR, GPIO_IDR_IDR_0)){

			i++;

			if(i==6){
				i=0;
			}

		}
		else
		{
			GPIOA->ODR = led_dice[i]<<4;
			GPIOC->ODR = seg[i];
		}


	}
}


void delay(uint32_t delay_ms){
	uint32_t current = msTicks;
		while (msTicks <(current + delay_ms)){
		  	  __WFE();
		}
}
