/*
******************************************************************************
File:     stm32f4xx_it.h
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-04-04

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __STM32F4xx_IT_H
#define __STM32F4xx_IT_H

#ifdef __cplusplus
 extern "C" {
#endif 

/* Includes ------------------------------------------------------------------*/
#include "stm32f4xx.h"

/* Exported types ------------------------------------------------------------*/
/* Exported constants --------------------------------------------------------*/

 /* Exported macro ------------------------------------------------------------*/
#define SET_BIT(REG, BIT) ((REG) |= (BIT))
#define CLEAR_BIT(REG, BIT) ((REG) &= ~(BIT))

 /* Exported functions ------------------------------------------------------- */

void NMI_Handler(void);
void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);
void UsageFault_Handler(void);
void SVC_Handler(void);
void DebugMon_Handler(void);
void PendSV_Handler(void);
void SysTick_Handler(void);

#ifdef __cplusplus
}
#endif

 /****************** Bits definition for GPIO_MODER register *****************/

#define GPIO_MODER_MODER0		((uint32_t)0x00000003)
#define GPIO_MODER_MODER0_0		((uint32_t)0x00000001)
#define GPIO_MODER_MODER0_1 	((uint32_t)0x00000002)
#define GPIO_MODER_MODER1 		((uint32_t)0x0000000C)
#define GPIO_MODER_MODER1_0 	((uint32_t)0x00000004)
#define GPIO_MODER_MODER1_1 	((uint32_t)0x00000008)
#define GPIO_MODER_MODER2 		((uint32_t)0x00000030)
#define GPIO_MODER_MODER2_0 	((uint32_t)0x00000010)
#define GPIO_MODER_MODER2_1 	((uint32_t)0x00000020)

#endif /* __STM32F4xx_IT_H */
